### ISSUE TITLE
HTML file references with query strings return index.html

### ISSUE THREAD

**Issue by Nibblesh** [fab-spec/fab#11]
The fab server will serve index.html if the request to a different html file contains a query

e.g.
/file.html returns file.html

/file.html?query returns index.html

**Comment by geelen** [comment]
This is using `fab-static` yeah?

**Comment by evanderkoogh** [comment]
Yeah.. I just took a look.. https://github.com/fab-spec/fab/blob/be590f2be4c6559534469b95aafe60ba16f844ab/packages/fab-static/src/files/fab-wrapper.js#L40

used `path`, but that should be `pathname`. Path includes the query string, pathname doesn't.

**Comment by evanderkoogh** [comment]
@Nibblesh I just released a prerelease version with a potential fix. Could you try out version `0.1.6-0`?

**Comment by Nibblesh** [comment]
Tried it out and this is working now! thanks guys

**Comment by evanderkoogh** [comment]
Just published version `0.1.6` proper. Thanks for reporting @Nibblesh
