### ISSUE TITLE
Lock down whether a "context" argument is needed.

### ISSUE THREAD

**Issue by geelen** [fab-spec/fab#116]
Use cases would be:

• Optional modules (like JS debugging) could be toggled with a server-set context variable. This could be done by Settings, but not clear if it should be.
• Expanded capabilities could be added here, like access to Cloudflare's cache API. Again, this could be supported by a standardised cache object passed down to the FAB, with noop implementations on other runtimes.

**Comment by evanderkoogh** [comment]
Everything we can do on the `context` object we could do with global variables in a FAB sandbox, some of which could be conventions in the settings object, but I much prefer the explicitness of a separate object with a type signature.

This would leave the settings object as a purely user-supplied flat JavaScript object and the `context` parameter as a way to give extra info and pass-in host supplied, potentially optional, functionality

So I think there are 2 categories to pass in. Extra information and functions. A list of things I can think of from the top of my head are:

Extra Information:
* `bundle_id`: This would be great for passing into Sentry, Bugsnag and other client-side error reporting tools
* Server hosting environment: What runtime are you running in.
* Server hosting intent?: We could be running with production settings, but the intent is not production traffic. We could be previewing or running automated tests.
* Host capabilities
* Host versions

Functions:
* Secure Token generation. Plain JavaScript has no good way of securely generating random data.
* Cache: A cache that is potentially used over multiple renders, especially in production. Can be used to cache data or intermediate or partial renders.
* CDN interactions: Invalidate all or particular URLs or preemptively put things in a cache for other URLs.
* Crypto APIs.

**Comment by geelen** [comment]
![FAB Diagram](https://user-images.githubusercontent.com/23264/80474763-c5a39b00-893f-11ea-957c-39b4cf9f4e1e.png)

**Comment by geelen** [comment]
Accident!

**Comment by geelen** [comment]
Ok this works, but I think it should be all passed in at FAB bootup, not per-request. I think this becomes available on the `Runtime.context` object inside a plugin, so you can decide which responders to attach based on whether the host supports something or not.

**Comment by geelen** [comment]
This is implemented as `ServerContext` on FABRuntime, and now includes caching layer. See #193
