### ISSUE TITLE
Inject commit SHA or bundle ID into FAB, for things like Rollbar

### ISSUE THREAD

**Issue by evanderkoogh** [fab-spec/fab#12]
In https://github.com/bitgenics/linc/issues/14 @qnm mentioned he needs a way to set a unique value for Rollup that changes whenever the Javascript source changes.

Right now the work-around is to use the repository tree_id, but that isn't ideal, because now the bundle changes on every repository change, even if that change never got into the bundle.

With a pre-package hook in `fab-compile` we could do something like calculate a checksum of the client JavaScript assets and set that as a id in the settings.

**Comment by geelen** [comment]
Wait so does the value need to go _into_ the bundle? Seems weird to have it as part of @fab/compile? You could do a md5sum on the `build` dir before kicking off `@fab/static`?

**Comment by evanderkoogh** [comment]
Hmm.. I guess that is possible indeed! But it has to go into the settings file, but I guess you can have a different template settings file that you copy into the one `fab-static` needs..

**Comment by geelen** [comment]
Sorry, still confused.

The "unique value for Rollup". Is that needed at build time or run time?

**Comment by qnm** [comment]
@geelen Build time. A Git SHA would be sufficient.

To clarify, it’s for Rollbar. The purpose is to distinguish source maps.

**Comment by geelen** [comment]
This should now be possible with a build-time plugin: https://fab.dev/kb/plugins

Might make for an interesting use-case, something that attaches the current `git_sha` to the `ProtoFab.metadata`. Will keep it in the back of my mind for post v1 launch.

**Comment by geelen** [comment]
https://github.com/fab-spec/plugin-add-fab-id uses this information from the context argument, hopefully that's enough of an example to wire this up? It's only the bundle_id, though with a build plugin there'd be nothing stopping you from injecting the git sha as well.

**Comment by qnm** [comment]
@geelen Feels like it would be enough. I'll have a crack at integrating it.

**Comment by qnm** [comment]
@geelen Does the `bundle_id` exist when building via webpack? If so, how do I access it? Feel free to point me to TFM :)

**Comment by evanderkoogh** [comment]
@qnm, no, the `bundle_id` is passed at runtime through the `ServerContext` that is part of the `FABRuntime`, as you can see at: https://github.com/fab-spec/plugin-add-fab-id/blob/f7f2785a192650296f222c30ab6d39f489a7d71c/index.ts#L14

Do you currently configure your Rollbar at webpack compile time?

**Comment by qnm** [comment]
This is for sourcemaps, so for context the process is roughly this:

1. build occurs, assets are created, including sourcemaps
1. we pick a unique id, could be a built identifier, or a git SHA
1. sourcemaps are loaded into Rollbar using e.g. `curl` or https://github.com/thredup/rollbar-sourcemap-webpack-plugin, containing the the ID in (2) as part of the payload
1. rollbar runtime is configured using the same id in (2). this allows the running code to be associated with the correct source map

How can I have an ID available at both compile-time and run-time?

I'm assuming that loading source maps into Rollbar at run-time is a bad idea.

**Comment by evanderkoogh** [comment]
Oh yeah, loading sourcemaps at runtime is absolutely a terrible idea :)

The problem is that a `bundle_id` is a hash of the entire FAB, so can only be made after the entire FAB has been built, which is well after webpack finished.

So I think the ideal solution would be to generate the sourcemaps during built, figure out the `bundle_id` after FAB is built and upload them to Rollbar with the `bundle_id`. And then use the `ServerContext.bundle_id` to pass that on to HTML.

That will also bundle your errors for commits where the code was actually the same.

But it will probably be easier to just get the `commit_sha` during build and use that as normal.

I'll try to find some time to sit with @geelen to see if it is possible to capture this logic in a FAB plugin. Would be great to be able to solve this for any FAB once and for all :)
