### ISSUE TITLE
Should we call it @fab/afterjs or @fab/razzle?

### ISSUE THREAD

**Issue by jaredpalmer** [fab-spec/fab#15]

**Comment by geelen** [comment]
Sounds good to me, `@fab/afterjs` was just my first attempt to get an SSR project off the ground. It worked! But I haven't looked at it since.

Any idea what it'd take to make it general purpose for razzle instead of explicitly afterjs?

**Comment by evanderkoogh** [comment]
@jaredpalmer Our ultimate goal is actually to not have it in here, but natively in either `razzle` or `afterjs`.
I know @geelen has been working hard on the `nextjs` stuff, and `cra` is next, but could be worth having a peek at making it work for razzle. Would love to see that one run on Cloudflare Workers ;)

**Comment by geelen** [comment]
Haven't really kept up any razzle/afterjs support here for v1, sorry. Will circle back around to it afterwards, but for now, only static sites & NextJS are targeted for v1.
