### ISSUE TITLE
Fetch not found in next.js project

### ISSUE THREAD

**Issue by aulneau** [fab-spec/fab#174]
This looks great! really want to see how this works with our next.js applications.

![Screen Shot 2020-05-14 at 11 32 56 AM](https://user-images.githubusercontent.com/11803153/81960570-c6425f80-95d6-11ea-857c-ef625a36aa64.png)

Seems to fail when trying to serve. I'm using next@9.4.0.

**Comment by geelen** [comment]
Damn, I'd only tested when you add `node-fetch` yourself, which still works with 9.4. I guess the new inbuilt fetch does something different...

Raised #176 to track the fix. Thanks for the report!

**Comment by geelen** [comment]
Oh, that's strange. I changed the E2E test to use the inbuilt fetch and it passed first time.

How is your app including `fetch`?

**Comment by aulneau** [comment]
I'm not including fetch due to it being bundled into next.js. I just ran npx fab.. etc again and it gave the same error.
