### ISSUE TITLE
[@fab/deployer-aws-*] Credential Sourcing

### ISSUE THREAD

**Issue by thejuan** [fab-spec/fab#180]
AWS SDK already has a pattern for sourcing credentials
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html

By explicitly forcing users to provide key and secret you break the other flows such as AWS_PROFILE  

Work around is to use a thirdparty cli tool for generating temp creds before hand such as https://www.npmjs.com/package/aws-assume for legacy apps

**Edit:** Get a token invalid error using the above, had to monkey patch

**Comment by thejuan** [comment]
Once I'm up and running, will look at PR

**Comment by geelen** [comment]
Fixed in 182
