### ISSUE TITLE
Local plugins written in TypeScript are not properly resolved

### ISSUE THREAD

**Issue by yacinehmito** [fab-spec/fab#205]
This is a bug report. Tested on 1.0.0-rc.4 and 1.0.0-rc.5

# Summary

When writing a local plugin in TypeScript, one needs to explicitly provide the path to the file, with the file extension. Relying on the automatic resolution does not work.

# Steps to reproduce

- Initialise a FAB project.
- In the directory, create the file `./server/myPlugin/runtime.ts`.
- In the `fab.config.json5`, in the `plugins` object, add `'./server/myPlugin: {}`.
- Run `fab build`.

# Expected result

The FAB builds with the plugin in `./server/myPlugin`.

# Actual result

It prints in the console:

```
The plugin './server/myPlugin' could not be found!
Looked for /Users/foo/bar/server/myPlugin/build, /Users/foo/bar/server/myPlugin/runtime & /Users/foo/bar/server/myPlugin
```

Replacing `'./server/myPlugin: {}` by `'./server/myPlugin/runtime.ts: {}` in `fab.config.json5` does work, which makes me think that the resolution algorithm only looks for JS files.

**Comment by yacinehmito** [comment]
So I dug [into the code](https://github.com/yacinehmito/fab/blob/aafa69a1fb663384770cd5e519566dd0a81d8948/packages/actions/src/Builder.ts#L98) a bit and I think I understand why this is happening: the resolution [relies on `require.resolve`](https://github.com/yacinehmito/fab/blob/aafa69a1fb663384770cd5e519566dd0a81d8948/packages/actions/src/Builder.ts#L18), which naturally assumes the source to be in JS.
The fact that it works with `./server/myPlugin/runtime.ts` is somewhat unintended. Because the file already has an extension, `require.resolve` is happy with it. Then, when it gets actually required, it fails. But, because [the call is wrapped in a `try/catch`](https://github.com/yacinehmito/fab/blob/aafa69a1fb663384770cd5e519566dd0a81d8948/packages/actions/src/Builder.ts#L24), it is then silenced, and we end up [forwarding the path normally](https://github.com/yacinehmito/fab/blob/aafa69a1fb663384770cd5e519566dd0a81d8948/packages/actions/src/Builder.ts#L174).

It looks like a proper fix for this would be quite involved. I'll come up with a proposition.

**Comment by geelen** [comment]
Damn, I have a simple fix but the testing infrastructure has `ts-node` included so I can't actually make it fail (since the tests themselves are written in typescript). Bit annoying, so I'll push this version with the latest releases and see if it solves it well enough for now.
