### ISSUE TITLE
"server" is a peculiar value for the NODE_ENV environment variable

### ISSUE THREAD

**Issue by yacinehmito** [fab-spec/fab#207]
I am submitting an issue for this but it's not very important, and a bit in the realm of opinions.

The gist of it: I find it weird to set `NODE_ENV` to `"server"` in the server'sruntime context.

There is no spec that describes that values that `NODE_ENV` can and should have. However, in the wild the consensus is usually that:

- `"development"` or `undefined` means that the program is running in development mode
- `"production"` means that the program is running in production mode
- `"test"` means that program is running in a test context

The fact that arbitrary values in `NODE_ENV` is somewhat unadvised is supported by the following resources:

- [Gatsby documentation](https://www.gatsbyjs.org/docs/environment-variables/#additional-environments-staging-test-etc)
- [Express documentation](https://expressjs.com/en/advanced/best-practice-performance.html#set-node_env-to-production)
- [Create-react-app documentation](https://create-react-app.dev/docs/adding-custom-environment-variables/)

Tooling and libraries do rely on those values. Setting it to `"server"` in the worker context is somewhat surprising.

**Comment by geelen** [comment]
This was actually copied directly from @evanderkoogh's code and I'd never even thought about it. I think `production` makes the most sense. Changing it now.
