### ISSUE TITLE
Document an overview of how routing works server-side

### ISSUE THREAD

**Issue by evanderkoogh** [fab-spec/fab#217]
Right now from the examples it seems like it is possible to do at least things like parameters and regexes, but what exactly is undocumented.

**Comment by geelen** [comment]
Sure, PR's welcomed! We just use [path-to-regexp](https://github.com/pillarjs/path-to-regexp) [behind the scenes](https://github.com/fab-spec/fab/blob/master/packages/core/src/runtime.ts#L66) which is passed through here: https://github.com/fab-spec/fab/blob/master/packages/core/src/runtime.ts#L72-L76

This can be a new page in the new [plugins section](https://github.com/fab-spec/fab/tree/master/docs/content/en/plugins) of the docs, ideally.

**Comment by evanbb** [comment]
howdy! i'd like to take this on if no one else has claimed it :)

i pulled down the repo and started following the contributing docs and discovered a few things requiring corrections - i am inclined to create a separate issue and PR for those before tackling this. that would also have a much quicker turnaround as i familiarize myself with running a FAB locally and routing. i just got a very simple url rewriter hooked up, similar to what is in the docs - super cool stuff!

**Comment by geelen** [comment]
Thanks for taking a look at this, I'll reply to your other issues and PRs :)
