### ISSUE TITLE
`@fab/plugin-rewire-assets` should chunk very large assets

### ISSUE THREAD

**Issue by geelen** [fab-spec/fab#240]
Add a `max_asset_size` to the plugin config, where if the file is larger, we split it up (and yes I'm going to use `~1` naming convention shout out to my DOS hax days) then add a server to stitch them back together.

Can't do it by default since not every FAB will have the server running in front of the `_assets`. But if the paths have been rewritten, maybe we can add it then?

Best default to `10 MB` (to match the Cloudflare [KV limits](https://developers.cloudflare.com/workers/platform/limits#kv)), so people never hit the error message in #239

**Comment by evanderkoogh** [comment]
Hey @geelen. Just thinking out loud here, but if we can't universally support this (and we can't, not on the hosting provider or on `/_assets/*` URLs), shouldn't this be a plugin?

If only a `@fab/plugin-rewire-assets-large` plugin that includes the stuff that just uses `@fab/plugin-rewire-assets` to handle all the non-chunking logic?

**Comment by geelen** [comment]
A bit in two minds here, my feeling is that we'd leave `_assets` sacrosanct and only chunk assets that were actually rewritten, that way if you've got a CDN in front of the FAB it'll work as normal. For Lambda@Edge, where "mutable" asset rewrites aren't supported, this would potentially involve making any super-large assets "mutable" by default...

Wait, that's not going to make any sense to anyone but us. Ok I'm going to add something like the following to the docs to make this more accessible to everyone else:

> ### Why "asset rewiring" is a thing.
>
> A FAB has exactly two parts, a `server.js` file which is the compiled output of your plugin chain, and a directory of assets in a directory called `_assets`. These assets are special in a few ways that make FABs ideal for production frontend apps:
>
> * All static files are renamed to include a hash of their contents (if they don't have one already)
> * They're always served at `/_assets`, with `cache-control: immutable` headers
> * This means that, if you choose to, you can use a load-balancing rule at the CDN level to direct all `/_assets/*` requests _directly to your static file hosting_ (e.g. S3), bypassing your FAB server entirely.
>
> If your app _doesn't_ export an `_assets` directory (or if you have _any_ files outside it), then `@fab/plugin-rewire-assets` will move the files into position for you, rename them if necessary, and add the server-side code to "rewire" the requests, meaning that an asset like `/fonts/papyrus-5eva.woff` is available at `https://your.site/fonts/papyrus-5eva.woff` but _stored in the FAB_ as `/_assets/fonts/papyrus-5eva.a1b2c3d4.woff`. (Note: it'll also be available at `https://your.site/_assets/fonts/papyrus-5eva.a1b2c3d4.woff` which can be useful for testing, but your app usually won't have any knowledge of that URL)
> 
> ### "Mutable" vs "Immutable" assets
> 
> While the above setup "just works" for apps of basically any structure out of the box, there's one important issue to understand: **caching**.
> 
> As mentioned above, assets are served with `cache-control: immutable`, which means once a browser has downloaded the file, _it will never go back to the server to look for updates_ (for as long as the file stays in the local cache). When the filename is `papyrus-5eva.a1b2c3d4.woff`, that's fine, since any change to that file's contents will _also_ change the filename (that's what fingerprinting is, it's great).
> 
> The problem is, the _browser_ is seeing a URL `https://your.site/fonts/papyrus-5eva.woff`, i.e. a _non-fingerprinted_ URL. So when our FAB rewires it, it has to strip off the `cache-control: immutable` header or new versions of that file won't ever be downloaded by previous clients.
> So, assets outside of `_assets` are sorted into two categories, _immutable_ ones (where the filename already has a content fingerprint) and _mutable_ ones (where the FAB server has to strip off the cache header). This strategy works 100% fine on platforms like Cloudflare Workers and NodeJS, but causes a problem on AWS Lambda
> ### Incompatibility with AWS Lambda (@Edge)
> AWS Lambda, of all the hosting options for FABs, has a few annoying restrictions:
> * No streaming responses
> * Max size on responses (6mb on Lambda, 1mb on Lambda@Edge)
> This means that assets, which are commonly >1mb or >6mb, _can't be served through the FAB itself_. Instead, an asset "rewrite" can be achieved using an "origin request", which is basically an AWS-specific directive that says "instead of the URL you asked for, this is the URL you want". Unfortunately, that provides no ability for the FAB to intercept this response and change headers.
> Thankfully, due to first-class support for asset fingerprinting in bundlers like Webpack and others, _usually_ the only non-fingerprinted assets are files like `robots.txt`, `manifest.json`, `favicon.ico` or external files like vendored css or fonts. If these files stay below the 1mb (or 6mb if using non-edge Lambda) limit, the problem will never manifest. And if AWS change the limits in future, it will occur in future cases. Files that are fingerprinted can be any size.
> Alternatively, if you change your application to use `/_assets` URLs directly, you can bypass the whole issue (since no rewiring is needed at all). This is just something to keep in mind when considering AWS Lambda/Lambda@Edge as a host.

Does this make sense?

Might give this a day to settle in my head and revisit it to see whether a plugin/built-in behaviour is more appropriate.
