### ISSUE TITLE
Better context for fab.config.json5 file parse error

### ISSUE THREAD

**Issue by Rashmi-278** [fab-spec/fab#246]
There are some errors in fab.config.json5 file which are unidentifiable , the config file looks about right but it still gives the errors.

This is the output I get after running `npx fab deploy fab.zip `
`ERROR: Problem with config file.

Could not parse file at 'fab.config.json5'. Check that it is valid JSON5.

    Error: Config file contains errors!`

If it provided better context as in line number , it would be very helpful to debug the issue.

**Comment by evanderkoogh** [comment]
@Rashmi-278, it looks like an error in the JSON format, it gives slightly better error messages when the contents of the JSON are wrong. But could you either include the file here or email them to us at support at linc dot sh so I can double check?

**Comment by Rashmi-278** [comment]
{
  plugins: {  
    '@fab/input-nextjs': {
      dir: '.next'
    },
    '@fab/plugin-render-html': {
      fallback: false
    },
    '@fab/plugin-rewire-assets': {}
    },
      settings: {
        production: {
     
        },
      },
      deploy: {
       'cf-workers': {
            account_id: '@CF_WORKERS_ACCOUNT_ID',
            api_token: '@CF_WORKERS_API_TOKEN',
            workers_dev: true,
            script_name: 'nextdemo2',
              },
      'aws-s3': {
            access_key: '@S3_ACCESS_KEY',
            secret-key: '@S3_SECRET_KEY',
            region: 'ap-south-1',
            bucket_name: 'fab-assets-nextdemo2',
              },  
      },
} 

@evanderkoogh  yes sure. this is my file content

**Comment by Rashmi-278** [comment]
A bit more context on the issue , here is the list of all packages and their versions 

/opt/bitnami/node/lib
├── @fab/cli@1.0.0-rc.6
├── create-next-app@9.5.3
├── create-react-app@3.4.1
├── cross-fetch@3.0.6
├── express-generator@4.16.1
├── forever@1.0.0
├── json5@2.1.3
├── next@9.5.3
├── node-gyp@7.0.0
├── npm@6.14.6
├── react@16.13.1
├── react-dom@16.13.1
└── yarn@1.22.4

node v12.18.3

npm 6.14.6

Thank you

**Comment by evanderkoogh** [comment]
Solved the immediate issue via Discord, it was a hyphen instead of an underscore in `secret_key`. But the original issue still stands. It would be great if we could give more context as to where it is going wrong.

**Comment by Rashmi-278** [comment]
Thank you ! @evanderkoogh 
yes for sure ,context would be helpful. hoping to see that in the next update.

**Comment by geelen** [comment]
This was fixed in #247 and released in RC7.
