### ISSUE TITLE
[@fab/deploy-cf-workers] support for multiple routes for one worker 

### ISSUE THREAD

**Issue by wis** [fab-spec/fab#280]
Cloudflare Workers can have multiple routes, Wrangler supports linking a Worker to multiple routes with the `routes` key (list/array value).
Wrangler config example:
```
name = "worker"
type = "javascript"
account_id = "youraccountid"
# can change this line
# route = "example.com/foo/*"
# to this line
routes = ["example.com/foo/*", "example.com/bar/*"]
zone_id = "yourzoneid"
```
This is an important feature since there is a limit of 30 workers per account, I want to be frugal with the number of workers I deploy since I plan to deploy workers for many websites I have on CF, I don't want to have multiple workers for each website instead of using one worker for multiple routes of a website.

**Comment by manniL** [comment]
As #281 is merged now, this issue can be closed ☺️

**Comment by geelen** [comment]
🤙
