### ISSUE TITLE
.env.production leads to errors

### ISSUE THREAD

**Issue by awthwathje** [fab-spec/fab#319]
If you use `.env.production` file with some variables, FAB build produced with `fab build` cannot be served anymore with `fab serve fab.zip` due to:

`Failed to load env from .env.production TypeError: e.info is not a function`

`fab deploy` fails as well.

**Comment by geelen** [comment]
Ok I'll look into it, what is the (redacted) contents of your `.env.production` file?

**Comment by awthwathje** [comment]
Just a bunch of unrelated variables:

```
AUTH0_DOMAIN=example.com
AUTH0_CLIENT_ID=AAAaaAaAaAAaAA
AUTH0_CLIENT_SECRET=aAaaAAaAAaAA
AUTH0_REDIRECT_URI=https://example.com/api/callback
AUTH0_POST_LOGOUT_REDIRECT_URI=http:/example.com/
AUTH0_SESSION_COOKIE_SECRET=aaAAaAAaaAaAAaaaaAAAaA
```

**Comment by jjcroftiv** [comment]
I wanted to comment that it doesn't need to be .env.production.  I have the same issue with a .env file in my local dev environment.

**Comment by mishiyee** [comment]
I also have this issue.  Tried with both .env.local and .env
