### ISSUE TITLE
after first load not work nextjs api on cloudflare workers

### ISSUE THREAD

**Issue by HardCoreQual** [fab-spec/fab#342]
I create simple nextjs app with api
deploy on cloudflare workers
open site in browser  -  api work
reopen site or refresh tab - api not work

[test.zip](https://github.com/fab-spec/fab/files/5897963/test.zip)
add in fab.config.json5 your cloudflare account_id and token
npm run next build && npm run fab build && npm run fab deploy

**Comment by geelen** [comment]
Hey there, this is a nasty bug with a simple fix:

```js
// api/your-endpoint.js

export default (req, res) => {
  // your existing route code here
}

// Add this export:
export const config = {
  api: {
    bodyParser: false,
  },
}
```

From the config documented [here](https://nextjs.org/docs/api-routes/api-middlewares)

(If you're interested, this took a bunch of investigation which you can read about in #252)

**Comment by HardCoreQual** [comment]
Thank you!
