### ISSUE TITLE
How to debug: "Webpack compiled output headers do not match between page files!"

### ISSUE THREAD

**Issue by johnbrett** [fab-spec/fab#47]
Hi I've a pretty straight forward nextjs app, some dynamic pages, some static. 

I tried to build with Fab following the awesome React Day Berlin talk, but got hit with the following:

`[FAB:NextJS] Webpack compiled output headers do not match between page files!`

`Error: Unexpected compiled page output`

Any tips on debugging this ?

**Comment by geelen** [comment]
Ooh! That I thought may break one day but I really didn't expect it yet. I'm making some assumptions about the internal structure of a compiled Next app, which is always a risk, but I am seeing most sites still fine atm.

Can you post your project, or at least the `.next` directory zipped up, somewhere so I can see the structure?

**Comment by johnbrett** [comment]
It's not a public repo, but not very private :D what's the easiest way to do this? I can add you as a collaborator on the repo, or send you the `.next` zipped via email or something?

**Comment by geelen** [comment]
Add me as a collaborator if that's ok, I'll try to incorporate whatever the problem is into the v1 work I'm doing as an e2e test case. But the best first step would be to understand the problem and figure out if there's an immediate workaround.

**Comment by johnbrett** [comment]
I've added you. Will open an issue in the repo so you we can discuss there

**Comment by dennisroethig** [comment]
Hey, @geelen and @johnbrett we're currently looking into trialing some next.js stuff on Cloudflare workers and we're hoping we could give FAB a try.

Do you have any info that came out of this and also of where the `next` branch is in regards to next.js? We had a quick look but it looks like it's not in a state yet to work at all (commented out mostly)

Cheers, keen to hear your thoughts ❤️

**Comment by johnbrett** [comment]
My next repo was not very standard which caused problems with this. I never got round to resolving the issues, ran out of time! Gonna close this as I don't have time to follow up unfortunately!

**Comment by geelen** [comment]
Sorry I missed your comment @dennisroethig I saw the issue get closed and didn't dive deeper.

Currently working on the NextJS FAB integration in line for a beta release this week. I ended up having to rip out the regexp stuff that was causing this exact issue but that's coming along nicely. Turns out hacking an AST isn't much harder than string matching, and is probably gonna be way more resilient.
