### ISSUE TITLE
Add typechecking to the rollup build.

### ISSUE THREAD

**Issue by geelen** [fab-spec/fab#65]
At the moment we just strip types during compilation, which is fine because your IDE probably helps you write small plugins that work, but it'd be nice to typecheck TS files as they get rolled up.

I genuinely don't understand Typescript well enought to know how to do that seamlessly, so this is a HELP WANTED issue 🙏

**Comment by geelen** [comment]
@mjackson might have brought the goods: https://github.com/ReactTraining/react-router/blob/dev/scripts/rollup/tsc-plugin.js

**Comment by Jarvis1010** [comment]
Is the goal to abort if types don’t check?

**Comment by geelen** [comment]
Ideally yeah, or at least have a big blazing warning. The problem is, Rollup doesn't care about the types themselves, it just strips them out. So you might have a file with invalid type declarations but rollup sees valid JS and is happy to consume them.

@mjackson's approach might work here, just spawn off `tsc --noEmit` on the file, I'm just not sure how fast that'll be, what `tsconfig.json` gets used etc.

**Comment by Jarvis1010** [comment]
ok I'll look at it and see if I can figure it out

**Comment by geelen** [comment]
This was released in RC5
