### ISSUE TITLE
@fab/serve blows up on current minimum node.js engine

### ISSUE THREAD

**Issue by colingourlay** [fab-spec/fab#7]
Support for `URL` global wasn't added until node.js v10, and this package specifies Node 8 as the minimum `engine` version.

When I run `fab-serve fab.zip` or `npx @fab/serve fab.zip` with node.js v8, I get:

```
ReferenceError: URL is not defined
    at Server.start (~/.nvm/versions/node/v8.11.4/lib/node_modules/@fab/serve/lib/Server.js:54:18)
    at <anonymous>
```

Bump dat minimum version to 10 and you're golden 👌

**Comment by evanderkoogh** [comment]
Cheers, thanks @colingourlay. I have just updated the minimum version. Will go out with the latest release :)
