### ISSUE TITLE
Docz is breaking link on homepage?

### ISSUE THREAD

**Issue by geelen** [fab-spec/fab#76]
On https://fab.dev/, the link to the original docs https://fab-docs--production--v0.branch.linc-preview.sh gets replaced with the link to the discord https://discord.gg/Qvj3pJY. No idea how this is happening, but the markup is right, in dev mode it's right, and when the page initially loads on fab.dev it's right. It's only once the Gatsby stuff picks up and rehydrates (I think?) that the link changes...

+@rakannimer thoughts?

**Comment by rakannimer** [comment]
It looks like there's a bug with the mdx parser when HTML is wrapped with markdown (banner image on homepage). I'll make a PR with a quick fix.
