### ISSUE TITLE
It'd be cool if @fab/serve could optionally run an https server

### ISSUE THREAD

**Issue by colingourlay** [fab-spec/fab#8]
`@fab/serve` is great for local verification of `@fab/static` apps, but sometimes those apps need to run under https (for location/device access, service workers etc.).

Usually browsers make exceptions for those sorts of cases when running on `localhost`, but you might need to fiddle with settings in dev tools to get everything working.

I've been using a dirty proxy server that passes requests through (or now): https://github.com/colingourlay/fab-serve-https-proxy

**Comment by evanderkoogh** [comment]
Hey @colingourlay, you are absolutely right. There are so many things now that require HTTPS or are next to impossible to test without HTTPS (looking at your CSP headers!).

I have created PR #9 to add support for it, but seeing as this was my first foray into Typescript I'll have @geelen review it before merging and releasing it.

**Comment by evanderkoogh** [comment]
Added in ‘@fab/serve:0.2.2’. If you could try giving it a spin and let us now?

**Comment by colingourlay** [comment]
Once I got to grips with `mkcert` and the environment settings for SSL with Node, this all worked perfectly. Thank you!
